development: &default
  adapter: postgresql
  encoding: unicode
  database: edifybot_development
  pool: 5
  username: postgres
  password:
  host: edifybot-db

test:
  <<: *default
  database: edifybot_test

production:
  adapter: postgresql
  database: edifybot 
  url: <%= ENV['DATABASE_URL'] %>