default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  host: expensetracker_db

development:
  <<: *default
  database: expensetracker_development

test:
  <<: *default
  database: expensetracker_test

production:
  <<: *default
  database: expensetracker 
