default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  host: edifybot-db

development:
  <<: *default
  database: edifybot_development

test:
  <<: *default
  database: edifybot_test

production:
  <<: *default
  database: edifybot 
  url: <%= ENV['DATABASE_URL'] %>