default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres

development:
  <<: *default
  host: edifybot-db
  database: edifybot_development

test:
  <<: *default
  host: edifybot-db
  database: edifybot_test

production:
  adapter: postgresql
  database: edifybot 
  url: <%= ENV['DATABASE_URL'] %>